# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WizardUsuario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(499, 354)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.label = QtGui.QLabel(self.wizardPage1)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.labelFormatoDataSet = QtGui.QLabel(self.wizardPage1)
        self.labelFormatoDataSet.setGeometry(QtCore.QRect(20, 40, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelFormatoDataSet.setFont(font)
        self.labelFormatoDataSet.setObjectName(_fromUtf8("labelFormatoDataSet"))
        self.comboBoxFormatoDataSet = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxFormatoDataSet.setGeometry(QtCore.QRect(140, 40, 121, 22))
        self.comboBoxFormatoDataSet.setObjectName(_fromUtf8("comboBoxFormatoDataSet"))
        self.comboBoxFormatoDataSet.addItem(_fromUtf8(""))
        self.comboBoxFormatoDataSet.addItem(_fromUtf8(""))
        self.pushButtonConfirmarFormato = QtGui.QPushButton(self.wizardPage1)
        self.pushButtonConfirmarFormato.setGeometry(QtCore.QRect(330, 40, 131, 23))
        self.pushButtonConfirmarFormato.setObjectName(_fromUtf8("pushButtonConfirmarFormato"))
        self.lineEditPadSequence = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditPadSequence.setGeometry(QtCore.QRect(140, 110, 61, 21))
        self.lineEditPadSequence.setObjectName(_fromUtf8("lineEditPadSequence"))
        self.labelMaxLongitud = QtGui.QLabel(self.wizardPage1)
        self.labelMaxLongitud.setGeometry(QtCore.QRect(220, 100, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelMaxLongitud.setFont(font)
        self.labelMaxLongitud.setObjectName(_fromUtf8("labelMaxLongitud"))
        self.labelPadSequence = QtGui.QLabel(self.wizardPage1)
        self.labelPadSequence.setGeometry(QtCore.QRect(20, 100, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelPadSequence.setFont(font)
        self.labelPadSequence.setObjectName(_fromUtf8("labelPadSequence"))
        self.labelTipoSplit = QtGui.QLabel(self.wizardPage1)
        self.labelTipoSplit.setGeometry(QtCore.QRect(20, 190, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTipoSplit.setFont(font)
        self.labelTipoSplit.setObjectName(_fromUtf8("labelTipoSplit"))
        self.comboBoxTipoSampling = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxTipoSampling.setGeometry(QtCore.QRect(140, 150, 151, 22))
        self.comboBoxTipoSampling.setObjectName(_fromUtf8("comboBoxTipoSampling"))
        self.comboBoxTipoSampling.addItem(_fromUtf8(""))
        self.comboBoxTipoSampling.addItem(_fromUtf8(""))
        self.comboBoxTest = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxTest.setGeometry(QtCore.QRect(390, 200, 71, 22))
        self.comboBoxTest.setObjectName(_fromUtf8("comboBoxTest"))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.labelTTValor = QtGui.QLabel(self.wizardPage1)
        self.labelTTValor.setGeometry(QtCore.QRect(340, 190, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTTValor.setFont(font)
        self.labelTTValor.setObjectName(_fromUtf8("labelTTValor"))
        self.labelTipoSampling = QtGui.QLabel(self.wizardPage1)
        self.labelTipoSampling.setGeometry(QtCore.QRect(20, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTipoSampling.setFont(font)
        self.labelTipoSampling.setObjectName(_fromUtf8("labelTipoSampling"))
        self.comboBoxTipoSplit = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxTipoSplit.setGeometry(QtCore.QRect(140, 200, 151, 22))
        self.comboBoxTipoSplit.setObjectName(_fromUtf8("comboBoxTipoSplit"))
        self.comboBoxTipoSplit.addItem(_fromUtf8(""))
        self.comboBoxTipoSplit.addItem(_fromUtf8(""))
        self.pushButtonPreproceso = QtGui.QPushButton(self.wizardPage1)
        self.pushButtonPreproceso.setGeometry(QtCore.QRect(330, 250, 131, 23))
        self.pushButtonPreproceso.setObjectName(_fromUtf8("pushButtonPreproceso"))
        self.pushButtonViewBalance = QtGui.QPushButton(self.wizardPage1)
        self.pushButtonViewBalance.setGeometry(QtCore.QRect(180, 130, 131, 23))
        self.pushButtonViewBalance.setObjectName(_fromUtf8("pushButtonViewBalance"))
        self.pushButtonViewBalance_2 = QtGui.QPushButton(self.wizardPage1)
        self.pushButtonViewBalance_2.setGeometry(QtCore.QRect(330, 80, 131, 23))
        self.pushButtonViewBalance_2.setObjectName(_fromUtf8("pushButtonViewBalance_2"))
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.label_2 = QtGui.QLabel(self.wizardPage2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButtonAddCapa = QtGui.QPushButton(self.wizardPage2)
        self.pushButtonAddCapa.setGeometry(QtCore.QRect(330, 230, 131, 23))
        self.pushButtonAddCapa.setObjectName(_fromUtf8("pushButtonAddCapa"))
        self.lineEditOutputLayer = QtGui.QLineEdit(self.wizardPage2)
        self.lineEditOutputLayer.setGeometry(QtCore.QRect(140, 150, 61, 21))
        self.lineEditOutputLayer.setObjectName(_fromUtf8("lineEditOutputLayer"))
        self.labelRate = QtGui.QLabel(self.wizardPage2)
        self.labelRate.setGeometry(QtCore.QRect(330, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        self.labelRate.setFont(font)
        self.labelRate.setObjectName(_fromUtf8("labelRate"))
        self.comboBoxActivation = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxActivation.setGeometry(QtCore.QRect(140, 110, 151, 22))
        self.comboBoxActivation.setObjectName(_fromUtf8("comboBoxActivation"))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.labelTipoCapa = QtGui.QLabel(self.wizardPage2)
        self.labelTipoCapa.setGeometry(QtCore.QRect(10, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelTipoCapa.setFont(font)
        self.labelTipoCapa.setObjectName(_fromUtf8("labelTipoCapa"))
        self.comboBoxRate = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxRate.setGeometry(QtCore.QRect(380, 60, 71, 22))
        self.comboBoxRate.setObjectName(_fromUtf8("comboBoxRate"))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxReturnSequencesLSTM = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxReturnSequencesLSTM.setGeometry(QtCore.QRect(140, 190, 71, 22))
        self.comboBoxReturnSequencesLSTM.setObjectName(_fromUtf8("comboBoxReturnSequencesLSTM"))
        self.comboBoxReturnSequencesLSTM.addItem(_fromUtf8(""))
        self.comboBoxReturnSequencesLSTM.addItem(_fromUtf8(""))
        self.labelOutputLayer = QtGui.QLabel(self.wizardPage2)
        self.labelOutputLayer.setGeometry(QtCore.QRect(10, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelOutputLayer.setFont(font)
        self.labelOutputLayer.setObjectName(_fromUtf8("labelOutputLayer"))
        self.labelReturnSequences = QtGui.QLabel(self.wizardPage2)
        self.labelReturnSequences.setGeometry(QtCore.QRect(10, 180, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelReturnSequences.setFont(font)
        self.labelReturnSequences.setObjectName(_fromUtf8("labelReturnSequences"))
        self.comboBoxTipoCapa = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxTipoCapa.setGeometry(QtCore.QRect(140, 60, 151, 22))
        self.comboBoxTipoCapa.setObjectName(_fromUtf8("comboBoxTipoCapa"))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.labelActivation = QtGui.QLabel(self.wizardPage2)
        self.labelActivation.setGeometry(QtCore.QRect(10, 100, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelActivation.setFont(font)
        self.labelActivation.setObjectName(_fromUtf8("labelActivation"))
        Wizard.addPage(self.wizardPage2)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.labelnNB_epoch = QtGui.QLabel(self.wizardPage)
        self.labelnNB_epoch.setGeometry(QtCore.QRect(20, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelnNB_epoch.setFont(font)
        self.labelnNB_epoch.setObjectName(_fromUtf8("labelnNB_epoch"))
        self.labelnNB_epoch_2 = QtGui.QLabel(self.wizardPage)
        self.labelnNB_epoch_2.setGeometry(QtCore.QRect(20, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelnNB_epoch_2.setFont(font)
        self.labelnNB_epoch_2.setObjectName(_fromUtf8("labelnNB_epoch_2"))
        self.pushButtonProceso = QtGui.QPushButton(self.wizardPage)
        self.pushButtonProceso.setGeometry(QtCore.QRect(330, 270, 131, 23))
        self.pushButtonProceso.setObjectName(_fromUtf8("pushButtonProceso"))
        self.lineEditNB_epoch = QtGui.QLineEdit(self.wizardPage)
        self.lineEditNB_epoch.setGeometry(QtCore.QRect(140, 230, 61, 21))
        self.lineEditNB_epoch.setObjectName(_fromUtf8("lineEditNB_epoch"))
        self.label_4 = QtGui.QLabel(self.wizardPage)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEditBatch = QtGui.QLineEdit(self.wizardPage)
        self.lineEditBatch.setGeometry(QtCore.QRect(140, 260, 61, 21))
        self.lineEditBatch.setObjectName(_fromUtf8("lineEditBatch"))
        self.label_3 = QtGui.QLabel(self.wizardPage)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 401, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.labelCompilerLoss = QtGui.QLabel(self.wizardPage)
        self.labelCompilerLoss.setGeometry(QtCore.QRect(20, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelCompilerLoss.setFont(font)
        self.labelCompilerLoss.setObjectName(_fromUtf8("labelCompilerLoss"))
        self.comboBoxCompilerLoss = QtGui.QComboBox(self.wizardPage)
        self.comboBoxCompilerLoss.setGeometry(QtCore.QRect(140, 120, 151, 22))
        self.comboBoxCompilerLoss.setObjectName(_fromUtf8("comboBoxCompilerLoss"))
        self.comboBoxCompilerLoss.addItem(_fromUtf8(""))
        self.comboBoxCompilerLoss.addItem(_fromUtf8(""))
        self.comboBoxCompilerLoss.addItem(_fromUtf8(""))
        self.comboBoxCompilerLoss.addItem(_fromUtf8(""))
        self.comboBoxCompilerLoss.addItem(_fromUtf8(""))
        self.labelCompilerOptimizer = QtGui.QLabel(self.wizardPage)
        self.labelCompilerOptimizer.setGeometry(QtCore.QRect(20, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelCompilerOptimizer.setFont(font)
        self.labelCompilerOptimizer.setObjectName(_fromUtf8("labelCompilerOptimizer"))
        self.comboBoxCompilerOptimizer = QtGui.QComboBox(self.wizardPage)
        self.comboBoxCompilerOptimizer.setGeometry(QtCore.QRect(140, 80, 151, 22))
        self.comboBoxCompilerOptimizer.setObjectName(_fromUtf8("comboBoxCompilerOptimizer"))
        self.comboBoxCompilerOptimizer.addItem(_fromUtf8(""))
        self.comboBoxCompilerOptimizer.addItem(_fromUtf8(""))
        self.comboBoxCompilerOptimizer.addItem(_fromUtf8(""))
        self.comboBoxCompilerOptimizer.addItem(_fromUtf8(""))
        self.comboBoxCompilerMetrics = QtGui.QComboBox(self.wizardPage)
        self.comboBoxCompilerMetrics.setGeometry(QtCore.QRect(140, 160, 151, 22))
        self.comboBoxCompilerMetrics.setObjectName(_fromUtf8("comboBoxCompilerMetrics"))
        self.comboBoxCompilerMetrics.addItem(_fromUtf8(""))
        self.comboBoxCompilerMetrics.addItem(_fromUtf8(""))
        self.comboBoxCompilerMetrics.addItem(_fromUtf8(""))
        self.labelCompilerLoss_2 = QtGui.QLabel(self.wizardPage)
        self.labelCompilerLoss_2.setGeometry(QtCore.QRect(20, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelCompilerLoss_2.setFont(font)
        self.labelCompilerLoss_2.setObjectName(_fromUtf8("labelCompilerLoss_2"))
        self.label_5 = QtGui.QLabel(self.wizardPage)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        Wizard.addPage(self.wizardPage)
        self.wizardPage_2 = QtGui.QWizardPage()
        self.wizardPage_2.setObjectName(_fromUtf8("wizardPage_2"))
        self.label_6 = QtGui.QLabel(self.wizardPage_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.labelTipoMetrica = QtGui.QLabel(self.wizardPage_2)
        self.labelTipoMetrica.setGeometry(QtCore.QRect(20, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(9)
        self.labelTipoMetrica.setFont(font)
        self.labelTipoMetrica.setObjectName(_fromUtf8("labelTipoMetrica"))
        self.comboBoxTipoMetrica = QtGui.QComboBox(self.wizardPage_2)
        self.comboBoxTipoMetrica.setGeometry(QtCore.QRect(140, 60, 151, 22))
        self.comboBoxTipoMetrica.setObjectName(_fromUtf8("comboBoxTipoMetrica"))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.pushButtonResultados = QtGui.QPushButton(self.wizardPage_2)
        self.pushButtonResultados.setGeometry(QtCore.QRect(330, 60, 131, 23))
        self.pushButtonResultados.setObjectName(_fromUtf8("pushButtonResultados"))
        Wizard.addPage(self.wizardPage_2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Red Neuronal", None))
        self.label.setText(_translate("Wizard", "PreProceso", None))
        self.labelFormatoDataSet.setText(_translate("Wizard", "Formato DataSet", None))
        self.comboBoxFormatoDataSet.setItemText(0, _translate("Wizard", "Formato 1", None))
        self.comboBoxFormatoDataSet.setItemText(1, _translate("Wizard", "Formato 2", None))
        self.pushButtonConfirmarFormato.setText(_translate("Wizard", "Confrimar Formato", None))
        self.lineEditPadSequence.setText(_translate("Wizard", "10", None))
        self.labelMaxLongitud.setText(_translate("Wizard", "Longitud", None))
        self.labelPadSequence.setText(_translate("Wizard", "Longitud instancia", None))
        self.labelTipoSplit.setText(_translate("Wizard", "Tipo Split", None))
        self.comboBoxTipoSampling.setItemText(0, _translate("Wizard", "OverSampling", None))
        self.comboBoxTipoSampling.setItemText(1, _translate("Wizard", "UnderSampling", None))
        self.comboBoxTest.setItemText(0, _translate("Wizard", "0.1", None))
        self.comboBoxTest.setItemText(1, _translate("Wizard", "0.2", None))
        self.comboBoxTest.setItemText(2, _translate("Wizard", "0.3", None))
        self.comboBoxTest.setItemText(3, _translate("Wizard", "0.4", None))
        self.comboBoxTest.setItemText(4, _translate("Wizard", "0.5", None))
        self.comboBoxTest.setItemText(5, _translate("Wizard", "0.6", None))
        self.comboBoxTest.setItemText(6, _translate("Wizard", "0.7", None))
        self.comboBoxTest.setItemText(7, _translate("Wizard", "0.8", None))
        self.comboBoxTest.setItemText(8, _translate("Wizard", "0.9", None))
        self.labelTTValor.setText(_translate("Wizard", "Test", None))
        self.labelTipoSampling.setText(_translate("Wizard", "Tipo Sampling", None))
        self.comboBoxTipoSplit.setItemText(0, _translate("Wizard", "TrainTest", None))
        self.comboBoxTipoSplit.setItemText(1, _translate("Wizard", "K-Fold", None))
        self.pushButtonPreproceso.setText(_translate("Wizard", "Pre-procesar", None))
        self.pushButtonViewBalance.setText(_translate("Wizard", "Mostrar Balanceo", None))
        self.pushButtonViewBalance_2.setText(_translate("Wizard", "Mostrar Balanceo", None))
        self.label_2.setText(_translate("Wizard", "PostProceso (crear Red)", None))
        self.pushButtonAddCapa.setText(_translate("Wizard", "Agregar Capa", None))
        self.lineEditOutputLayer.setText(_translate("Wizard", "10", None))
        self.labelRate.setText(_translate("Wizard", "Rate", None))
        self.comboBoxActivation.setItemText(0, _translate("Wizard", "softmax", None))
        self.comboBoxActivation.setItemText(1, _translate("Wizard", "softplus", None))
        self.comboBoxActivation.setItemText(2, _translate("Wizard", "tanh", None))
        self.comboBoxActivation.setItemText(3, _translate("Wizard", "sigmoid", None))
        self.comboBoxActivation.setItemText(4, _translate("Wizard", "linear", None))
        self.comboBoxActivation.setItemText(5, _translate("Wizard", "relu", None))
        self.labelTipoCapa.setText(_translate("Wizard", "Tipo Capa", None))
        self.comboBoxRate.setItemText(0, _translate("Wizard", "0.1", None))
        self.comboBoxRate.setItemText(1, _translate("Wizard", "0.2", None))
        self.comboBoxRate.setItemText(2, _translate("Wizard", "0.3", None))
        self.comboBoxRate.setItemText(3, _translate("Wizard", "0.4", None))
        self.comboBoxRate.setItemText(4, _translate("Wizard", "0.5", None))
        self.comboBoxRate.setItemText(5, _translate("Wizard", "0.6", None))
        self.comboBoxRate.setItemText(6, _translate("Wizard", "0.7", None))
        self.comboBoxRate.setItemText(7, _translate("Wizard", "0.8", None))
        self.comboBoxRate.setItemText(8, _translate("Wizard", "0.9", None))
        self.comboBoxReturnSequencesLSTM.setItemText(0, _translate("Wizard", "True", None))
        self.comboBoxReturnSequencesLSTM.setItemText(1, _translate("Wizard", "False", None))
        self.labelOutputLayer.setText(_translate("Wizard", "Output", None))
        self.labelReturnSequences.setText(_translate("Wizard", "Return Sequences", None))
        self.comboBoxTipoCapa.setItemText(0, _translate("Wizard", "Embedding", None))
        self.comboBoxTipoCapa.setItemText(1, _translate("Wizard", "Dense", None))
        self.comboBoxTipoCapa.setItemText(2, _translate("Wizard", "Dropout", None))
        self.comboBoxTipoCapa.setItemText(3, _translate("Wizard", "LSTM", None))
        self.labelActivation.setText(_translate("Wizard", "Activation", None))
        self.labelnNB_epoch.setText(_translate("Wizard", "nb_epoch", None))
        self.labelnNB_epoch_2.setText(_translate("Wizard", "batch_size", None))
        self.pushButtonProceso.setText(_translate("Wizard", "Procesar", None))
        self.lineEditNB_epoch.setText(_translate("Wizard", "10", None))
        self.label_4.setText(_translate("Wizard", "Entrenamiento Red", None))
        self.lineEditBatch.setText(_translate("Wizard", "10", None))
        self.label_3.setText(_translate("Wizard", "PostProceso (Compilación - Entrenamiento Red)", None))
        self.labelCompilerLoss.setText(_translate("Wizard", "loss", None))
        self.comboBoxCompilerLoss.setItemText(0, _translate("Wizard", "categorical_crossentropy", None))
        self.comboBoxCompilerLoss.setItemText(1, _translate("Wizard", "poisson", None))
        self.comboBoxCompilerLoss.setItemText(2, _translate("Wizard", "binary_crossentropy", None))
        self.comboBoxCompilerLoss.setItemText(3, _translate("Wizard", "mean_squared_error", None))
        self.comboBoxCompilerLoss.setItemText(4, _translate("Wizard", "mean_absolute_error", None))
        self.labelCompilerOptimizer.setText(_translate("Wizard", "Optimizer", None))
        self.comboBoxCompilerOptimizer.setItemText(0, _translate("Wizard", "rmsprop", None))
        self.comboBoxCompilerOptimizer.setItemText(1, _translate("Wizard", "adagrad", None))
        self.comboBoxCompilerOptimizer.setItemText(2, _translate("Wizard", "adadelta", None))
        self.comboBoxCompilerOptimizer.setItemText(3, _translate("Wizard", "adam", None))
        self.comboBoxCompilerMetrics.setItemText(0, _translate("Wizard", "categorical_accuracy", None))
        self.comboBoxCompilerMetrics.setItemText(1, _translate("Wizard", "binary_accuracy", None))
        self.comboBoxCompilerMetrics.setItemText(2, _translate("Wizard", "sparse_categorical_accuracy", None))
        self.labelCompilerLoss_2.setText(_translate("Wizard", "metrics", None))
        self.label_5.setText(_translate("Wizard", "Compilación Red", None))
        self.label_6.setText(_translate("Wizard", "PostProceso", None))
        self.labelTipoMetrica.setText(_translate("Wizard", "Tipo Metrica", None))
        self.comboBoxTipoMetrica.setItemText(0, _translate("Wizard", "Precision Score", None))
        self.comboBoxTipoMetrica.setItemText(1, _translate("Wizard", "Recall_score", None))
        self.comboBoxTipoMetrica.setItemText(2, _translate("Wizard", "zero_one_loss", None))
        self.comboBoxTipoMetrica.setItemText(3, _translate("Wizard", "accuracy_score", None))
        self.comboBoxTipoMetrica.setItemText(4, _translate("Wizard", "confusion_matrix", None))
        self.pushButtonResultados.setText(_translate("Wizard", "Mostrar Metricas", None))

