# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfazUsuario.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogUsuario(object):
    def setupUi(self, DialogUsuario):
        DialogUsuario.setObjectName(_fromUtf8("DialogUsuario"))
        DialogUsuario.resize(513, 629)
        self.pushButtonViewBalance = QtGui.QPushButton(DialogUsuario)
        self.pushButtonViewBalance.setGeometry(QtCore.QRect(30, 30, 131, 23))
        self.pushButtonViewBalance.setObjectName(_fromUtf8("pushButtonViewBalance"))
        self.labelPadSequence = QtGui.QLabel(DialogUsuario)
        self.labelPadSequence.setGeometry(QtCore.QRect(30, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPadSequence.setFont(font)
        self.labelPadSequence.setObjectName(_fromUtf8("labelPadSequence"))
        self.lineEditPadSequence = QtGui.QLineEdit(DialogUsuario)
        self.lineEditPadSequence.setGeometry(QtCore.QRect(150, 70, 61, 21))
        self.lineEditPadSequence.setObjectName(_fromUtf8("lineEditPadSequence"))
        self.labelTipoSampling = QtGui.QLabel(DialogUsuario)
        self.labelTipoSampling.setGeometry(QtCore.QRect(30, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTipoSampling.setFont(font)
        self.labelTipoSampling.setObjectName(_fromUtf8("labelTipoSampling"))
        self.comboBoxTipoSampling = QtGui.QComboBox(DialogUsuario)
        self.comboBoxTipoSampling.setGeometry(QtCore.QRect(150, 110, 151, 22))
        self.comboBoxTipoSampling.setObjectName(_fromUtf8("comboBoxTipoSampling"))
        self.comboBoxTipoSampling.addItem(_fromUtf8(""))
        self.comboBoxTipoSampling.addItem(_fromUtf8(""))
        self.labelTipoSplit = QtGui.QLabel(DialogUsuario)
        self.labelTipoSplit.setGeometry(QtCore.QRect(30, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTipoSplit.setFont(font)
        self.labelTipoSplit.setObjectName(_fromUtf8("labelTipoSplit"))
        self.comboBoxTipoSplit = QtGui.QComboBox(DialogUsuario)
        self.comboBoxTipoSplit.setGeometry(QtCore.QRect(150, 150, 151, 22))
        self.comboBoxTipoSplit.setObjectName(_fromUtf8("comboBoxTipoSplit"))
        self.comboBoxTipoSplit.addItem(_fromUtf8(""))
        self.comboBoxTipoSplit.addItem(_fromUtf8(""))
        self.comboBoxTest = QtGui.QComboBox(DialogUsuario)
        self.comboBoxTest.setGeometry(QtCore.QRect(400, 150, 71, 22))
        self.comboBoxTest.setObjectName(_fromUtf8("comboBoxTest"))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.comboBoxTest.addItem(_fromUtf8(""))
        self.labelTTValor = QtGui.QLabel(DialogUsuario)
        self.labelTTValor.setGeometry(QtCore.QRect(350, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTTValor.setFont(font)
        self.labelTTValor.setObjectName(_fromUtf8("labelTTValor"))
        self.label = QtGui.QLabel(DialogUsuario)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.labelNroClases = QtGui.QLabel(DialogUsuario)
        self.labelNroClases.setGeometry(QtCore.QRect(30, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNroClases.setFont(font)
        self.labelNroClases.setObjectName(_fromUtf8("labelNroClases"))
        self.lineEditNroClases = QtGui.QLineEdit(DialogUsuario)
        self.lineEditNroClases.setGeometry(QtCore.QRect(150, 190, 61, 21))
        self.lineEditNroClases.setObjectName(_fromUtf8("lineEditNroClases"))
        self.label_2 = QtGui.QLabel(DialogUsuario)
        self.label_2.setGeometry(QtCore.QRect(20, 230, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.labelTipoCapa = QtGui.QLabel(DialogUsuario)
        self.labelTipoCapa.setGeometry(QtCore.QRect(30, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTipoCapa.setFont(font)
        self.labelTipoCapa.setObjectName(_fromUtf8("labelTipoCapa"))
        self.comboBoxTipoCapa = QtGui.QComboBox(DialogUsuario)
        self.comboBoxTipoCapa.setGeometry(QtCore.QRect(150, 260, 151, 22))
        self.comboBoxTipoCapa.setObjectName(_fromUtf8("comboBoxTipoCapa"))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxTipoCapa.addItem(_fromUtf8(""))
        self.comboBoxActivation = QtGui.QComboBox(DialogUsuario)
        self.comboBoxActivation.setGeometry(QtCore.QRect(150, 300, 151, 22))
        self.comboBoxActivation.setObjectName(_fromUtf8("comboBoxActivation"))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.comboBoxActivation.addItem(_fromUtf8(""))
        self.labelActivation = QtGui.QLabel(DialogUsuario)
        self.labelActivation.setGeometry(QtCore.QRect(30, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelActivation.setFont(font)
        self.labelActivation.setObjectName(_fromUtf8("labelActivation"))
        self.labelOutputLayer = QtGui.QLabel(DialogUsuario)
        self.labelOutputLayer.setGeometry(QtCore.QRect(30, 330, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOutputLayer.setFont(font)
        self.labelOutputLayer.setObjectName(_fromUtf8("labelOutputLayer"))
        self.lineEditOutputLayer = QtGui.QLineEdit(DialogUsuario)
        self.lineEditOutputLayer.setGeometry(QtCore.QRect(150, 340, 61, 21))
        self.lineEditOutputLayer.setObjectName(_fromUtf8("lineEditOutputLayer"))
        self.pushButtonAddCapa = QtGui.QPushButton(DialogUsuario)
        self.pushButtonAddCapa.setGeometry(QtCore.QRect(340, 370, 131, 23))
        self.pushButtonAddCapa.setObjectName(_fromUtf8("pushButtonAddCapa"))
        self.label_3 = QtGui.QLabel(DialogUsuario)
        self.label_3.setGeometry(QtCore.QRect(20, 520, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.labelTipoMetrica = QtGui.QLabel(DialogUsuario)
        self.labelTipoMetrica.setGeometry(QtCore.QRect(30, 540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTipoMetrica.setFont(font)
        self.labelTipoMetrica.setObjectName(_fromUtf8("labelTipoMetrica"))
        self.comboBoxTipoMetrica = QtGui.QComboBox(DialogUsuario)
        self.comboBoxTipoMetrica.setGeometry(QtCore.QRect(150, 550, 151, 22))
        self.comboBoxTipoMetrica.setObjectName(_fromUtf8("comboBoxTipoMetrica"))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.comboBoxTipoMetrica.addItem(_fromUtf8(""))
        self.pushButtonAddMet = QtGui.QPushButton(DialogUsuario)
        self.pushButtonAddMet.setGeometry(QtCore.QRect(340, 550, 131, 23))
        self.pushButtonAddMet.setObjectName(_fromUtf8("pushButtonAddMet"))
        self.labelnNB_epoch = QtGui.QLabel(DialogUsuario)
        self.labelnNB_epoch.setGeometry(QtCore.QRect(30, 440, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelnNB_epoch.setFont(font)
        self.labelnNB_epoch.setObjectName(_fromUtf8("labelnNB_epoch"))
        self.lineEditNB_epoch = QtGui.QLineEdit(DialogUsuario)
        self.lineEditNB_epoch.setGeometry(QtCore.QRect(150, 450, 61, 21))
        self.lineEditNB_epoch.setObjectName(_fromUtf8("lineEditNB_epoch"))
        self.labelnNB_epoch_2 = QtGui.QLabel(DialogUsuario)
        self.labelnNB_epoch_2.setGeometry(QtCore.QRect(30, 470, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelnNB_epoch_2.setFont(font)
        self.labelnNB_epoch_2.setObjectName(_fromUtf8("labelnNB_epoch_2"))
        self.lineEditBatch = QtGui.QLineEdit(DialogUsuario)
        self.lineEditBatch.setGeometry(QtCore.QRect(150, 480, 61, 21))
        self.lineEditBatch.setObjectName(_fromUtf8("lineEditBatch"))
        self.comboBoxRate = QtGui.QComboBox(DialogUsuario)
        self.comboBoxRate.setGeometry(QtCore.QRect(400, 260, 71, 22))
        self.comboBoxRate.setObjectName(_fromUtf8("comboBoxRate"))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.comboBoxRate.addItem(_fromUtf8(""))
        self.labelRate = QtGui.QLabel(DialogUsuario)
        self.labelRate.setGeometry(QtCore.QRect(350, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelRate.setFont(font)
        self.labelRate.setObjectName(_fromUtf8("labelRate"))
        self.label_4 = QtGui.QLabel(DialogUsuario)
        self.label_4.setGeometry(QtCore.QRect(20, 420, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButtonPreproceso = QtGui.QPushButton(DialogUsuario)
        self.pushButtonPreproceso.setGeometry(QtCore.QRect(340, 190, 131, 23))
        self.pushButtonPreproceso.setObjectName(_fromUtf8("pushButtonPreproceso"))
        self.pushButtonProceso = QtGui.QPushButton(DialogUsuario)
        self.pushButtonProceso.setGeometry(QtCore.QRect(340, 480, 131, 23))
        self.pushButtonProceso.setObjectName(_fromUtf8("pushButtonProceso"))
        self.pushButtonResultados = QtGui.QPushButton(DialogUsuario)
        self.pushButtonResultados.setGeometry(QtCore.QRect(340, 590, 131, 23))
        self.pushButtonResultados.setObjectName(_fromUtf8("pushButtonResultados"))
        self.comboBoxReturnSequencesLSTM = QtGui.QComboBox(DialogUsuario)
        self.comboBoxReturnSequencesLSTM.setGeometry(QtCore.QRect(150, 370, 71, 22))
        self.comboBoxReturnSequencesLSTM.setObjectName(_fromUtf8("comboBoxReturnSequencesLSTM"))
        self.comboBoxReturnSequencesLSTM.addItem(_fromUtf8(""))
        self.comboBoxReturnSequencesLSTM.addItem(_fromUtf8(""))
        self.labelReturnSequences = QtGui.QLabel(DialogUsuario)
        self.labelReturnSequences.setGeometry(QtCore.QRect(30, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelReturnSequences.setFont(font)
        self.labelReturnSequences.setObjectName(_fromUtf8("labelReturnSequences"))

        self.retranslateUi(DialogUsuario)
        QtCore.QMetaObject.connectSlotsByName(DialogUsuario)

    def retranslateUi(self, DialogUsuario):
        DialogUsuario.setWindowTitle(_translate("DialogUsuario", "Red Neuronal", None))
        self.pushButtonViewBalance.setText(_translate("DialogUsuario", "Mostrar Balanceo", None))
        self.labelPadSequence.setText(_translate("DialogUsuario", "Longitud instancia", None))
        self.lineEditPadSequence.setText(_translate("DialogUsuario", "10", None))
        self.labelTipoSampling.setText(_translate("DialogUsuario", "Tipo Sampling", None))
        self.comboBoxTipoSampling.setItemText(0, _translate("DialogUsuario", "OverSampling", None))
        self.comboBoxTipoSampling.setItemText(1, _translate("DialogUsuario", "UnderSampling", None))
        self.labelTipoSplit.setText(_translate("DialogUsuario", "Tipo Split", None))
        self.comboBoxTipoSplit.setItemText(0, _translate("DialogUsuario", "TrainTest", None))
        self.comboBoxTipoSplit.setItemText(1, _translate("DialogUsuario", "K-Fold", None))
        self.comboBoxTest.setItemText(0, _translate("DialogUsuario", "0.1", None))
        self.comboBoxTest.setItemText(1, _translate("DialogUsuario", "0.2", None))
        self.comboBoxTest.setItemText(2, _translate("DialogUsuario", "0.3", None))
        self.comboBoxTest.setItemText(3, _translate("DialogUsuario", "0.4", None))
        self.comboBoxTest.setItemText(4, _translate("DialogUsuario", "0.5", None))
        self.comboBoxTest.setItemText(5, _translate("DialogUsuario", "0.6", None))
        self.comboBoxTest.setItemText(6, _translate("DialogUsuario", "0.7", None))
        self.comboBoxTest.setItemText(7, _translate("DialogUsuario", "0.8", None))
        self.comboBoxTest.setItemText(8, _translate("DialogUsuario", "0.9", None))
        self.labelTTValor.setText(_translate("DialogUsuario", "Test", None))
        self.label.setText(_translate("DialogUsuario", "PreProceso", None))
        self.labelNroClases.setText(_translate("DialogUsuario", "Nro_clases", None))
        self.lineEditNroClases.setText(_translate("DialogUsuario", "10", None))
        self.label_2.setText(_translate("DialogUsuario", "Proceso", None))
        self.labelTipoCapa.setText(_translate("DialogUsuario", "Tipo Capa", None))
        self.comboBoxTipoCapa.setItemText(0, _translate("DialogUsuario", "Embedding", None))
        self.comboBoxTipoCapa.setItemText(1, _translate("DialogUsuario", "Dense", None))
        self.comboBoxTipoCapa.setItemText(2, _translate("DialogUsuario", "Dropout", None))
        self.comboBoxTipoCapa.setItemText(3, _translate("DialogUsuario", "LSTM", None))
        self.comboBoxActivation.setItemText(0, _translate("DialogUsuario", "softmax", None))
        self.comboBoxActivation.setItemText(1, _translate("DialogUsuario", "softplus", None))
        self.comboBoxActivation.setItemText(2, _translate("DialogUsuario", "tanh", None))
        self.comboBoxActivation.setItemText(3, _translate("DialogUsuario", "sigmoid", None))
        self.comboBoxActivation.setItemText(4, _translate("DialogUsuario", "linear", None))
        self.labelActivation.setText(_translate("DialogUsuario", "Activation", None))
        self.labelOutputLayer.setText(_translate("DialogUsuario", "Output", None))
        self.lineEditOutputLayer.setText(_translate("DialogUsuario", "10", None))
        self.pushButtonAddCapa.setText(_translate("DialogUsuario", "Agregar Capa", None))
        self.label_3.setText(_translate("DialogUsuario", "PostProceso", None))
        self.labelTipoMetrica.setText(_translate("DialogUsuario", "Tipo Metrica", None))
        self.comboBoxTipoMetrica.setItemText(0, _translate("DialogUsuario", "Precision Score", None))
        self.comboBoxTipoMetrica.setItemText(1, _translate("DialogUsuario", "Recall_score", None))
        self.comboBoxTipoMetrica.setItemText(2, _translate("DialogUsuario", "zero_one_loss", None))
        self.comboBoxTipoMetrica.setItemText(3, _translate("DialogUsuario", "accuracy_score", None))
        self.comboBoxTipoMetrica.setItemText(4, _translate("DialogUsuario", "confusion_matrix", None))
        self.pushButtonAddMet.setText(_translate("DialogUsuario", "Agregar Metrica", None))
        self.labelnNB_epoch.setText(_translate("DialogUsuario", "nb_epoch", None))
        self.lineEditNB_epoch.setText(_translate("DialogUsuario", "10", None))
        self.labelnNB_epoch_2.setText(_translate("DialogUsuario", "batch_size", None))
        self.lineEditBatch.setText(_translate("DialogUsuario", "10", None))
        self.comboBoxRate.setItemText(0, _translate("DialogUsuario", "0.25", None))
        self.comboBoxRate.setItemText(1, _translate("DialogUsuario", "0.5", None))
        self.comboBoxRate.setItemText(2, _translate("DialogUsuario", "0.75", None))
        self.labelRate.setText(_translate("DialogUsuario", "Rate", None))
        self.label_4.setText(_translate("DialogUsuario", "Entrenamiento Red", None))
        self.pushButtonPreproceso.setText(_translate("DialogUsuario", "Pre-procesar", None))
        self.pushButtonProceso.setText(_translate("DialogUsuario", "Procesar", None))
        self.pushButtonResultados.setText(_translate("DialogUsuario", "Mostrar Metricas", None))
        self.comboBoxReturnSequencesLSTM.setItemText(0, _translate("DialogUsuario", "True", None))
        self.comboBoxReturnSequencesLSTM.setItemText(1, _translate("DialogUsuario", "False", None))
        self.labelReturnSequences.setText(_translate("DialogUsuario", "Return Sequences", None))

